#!/usr/bin/env python3
"""Generate a shell script that deletes redundant duplicate files.

Reads the 'hashes' table of a sqlite3 database (filename TEXT, hash TEXT,
mtime REAL -- see hash_dir.py) and, for every hash shared by more than
one file, picks a single "canonical" copy to keep and emits `rm`
commands for the rest.

This tool only WRITES a shell script, to stdout. It never deletes
anything itself; review the generated script before running it.

See ranking.py for the canonical-copy ranking heuristic (shared with
metadata_db.py).

Usage:
    cleanup.py
        --v=3
        --database ~/zoo.db
        > cleanup.sh
"""

import shlex
import sqlite3
import sys
from collections import defaultdict
from datetime import datetime, timezone

from absl import app
from absl import flags
from absl import logging

from ranking import rank

FLAGS = flags.FLAGS

flags.DEFINE_string("database", None, "Path to the sqlite3 database.")
flags.mark_flag_as_required("database")


def load_hashes(db_path):
    """Return dict: hash -> list of filenames, from the 'hashes' table."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        cur = conn.execute("SELECT hash, filename FROM hashes")
        hash_to_files = defaultdict(list)
        for hash_, filename in cur:
            hash_to_files[hash_].append(filename)
        return hash_to_files
    finally:
        conn.close()


def build_script(db_path, hash_to_files):
    lines = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by cleanup.py -- DO NOT RUN WITHOUT REVIEWING FIRST.")
    lines.append(f"# Source database: {db_path}")
    lines.append(f"# Generated at:    {datetime.now(timezone.utc).isoformat()}")
    lines.append("# Run from the directory that the paths below are relative to.")
    lines.append("set -e")
    lines.append("")

    groups = [(h, files) for h, files in hash_to_files.items() if len(files) > 1]
    groups.sort(key=lambda hf: rank(hf[1])[0])

    total_dup_files = sum(len(files) - 1 for _, files in groups)

    num_deleted = 0
    for h, files in groups:
        ranked = rank(files)
        canonical = ranked[0]
        duplicates = ranked[1:]
        logging.vlog(3, "Processing hash %s -- keeping %s, %d duplicate(s)",
                     h, canonical, len(duplicates))
        lines.append(f"# hash {h} -- keeping: {canonical}")
        for dup in duplicates:
            logging.vlog(5, "Marking duplicate for deletion: %s (hash %s)",
                         dup, h)
            lines.append(f"# duplicate of: {canonical}  (hash {h})")
            lines.append(f"rm -vf -- {shlex.quote(dup)}")
            num_deleted += 1

            if num_deleted % 100 == 0:
                pct = num_deleted / total_dup_files * 100
                lines.append(f"echo ======= Progress {pct:.2f}% ========")
        lines.append("")

    return "\n".join(lines) + "\n", len(groups), num_deleted


def main(argv):
    if len(argv) != 1:
        raise app.UsageError(
            "This tool takes no positional arguments; use --database "
            "instead (got: %s)" % argv[1:])

    hash_to_files = load_hashes(FLAGS.database)
    script, num_groups, num_deleted = build_script(FLAGS.database, hash_to_files)

    sys.stdout.write(script)

    logging.info("duplicate hash groups: %d", num_groups)
    logging.info("files marked for deletion: %d", num_deleted)
    logging.info("Review the script before running it -- nothing was deleted.")


if __name__ == "__main__":
    app.run(main)
