#!/usr/bin/env python3
"""Generate a shell script that removes empty directory trees.

Descends into every subdirectory of --dir and finds every directory
that is empty, or that transitively contains nothing but other such
empty directories (no files anywhere in the subtree). For each one,
emits an `rmdir` command, ordered deepest-first so a parent is only
removed after all of its now-empty children have been.

--dir itself is never included, even if the whole tree under it is
empty -- only its subdirectories are candidates for removal.

This tool only WRITES a shell script, to stdout. It never removes
anything itself; review the generated script before running it.

Usage:
    find_empty_dirs.py
        --dir /zoo/Pictures
        > find_empty_dirs.sh
"""

import os
import shlex
import sys
from datetime import datetime, timezone

from absl import app
from absl import flags
from absl import logging

FLAGS = flags.FLAGS

flags.DEFINE_string(
    "dir", None, "Directory to scan; its subdirectories are the removal "
    "candidates (the directory itself is never removed).")
flags.mark_flag_as_required("dir")


def find_removable_dirs(root_dir):
    """Return removable subdirectories of root_dir, deepest-first.

    A directory is removable if it contains no files and every one of
    its immediate subdirectories is itself removable (transitively --
    so a directory full of nothing but empty subdirectories counts).
    root_dir itself is never included in the result, even if it
    qualifies.
    """
    removable = set()
    order = []

    def on_error(err):
        logging.warning("Skipping %s: %s", getattr(err, "filename", err), err)

    for dirpath, dirnames, filenames in os.walk(
            root_dir, topdown=False, onerror=on_error):
        if filenames:
            continue
        if not all(os.path.join(dirpath, d) in removable for d in dirnames):
            continue
        removable.add(dirpath)
        if os.path.abspath(dirpath) != os.path.abspath(root_dir):
            order.append(dirpath)

    return order


def build_script(dir_arg, removable_dirs):
    lines = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by find_empty_dirs.py -- DO NOT RUN WITHOUT REVIEWING FIRST.")
    lines.append(f"# Scanned directory: {dir_arg}")
    lines.append(f"# Generated at:      {datetime.now(timezone.utc).isoformat()}")
    lines.append("set -e")
    lines.append("")

    for d in removable_dirs:
        lines.append(f"rmdir -v -- {shlex.quote(d)}")

    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) != 1:
        raise app.UsageError(
            "This tool takes no positional arguments; use --dir instead "
            "(got: %s)" % argv[1:])

    removable_dirs = find_removable_dirs(FLAGS.dir)
    script = build_script(FLAGS.dir, removable_dirs)

    sys.stdout.write(script)

    logging.info("%d empty directories to remove", len(removable_dirs))
    logging.info("Review the script before running it -- nothing was removed.")


if __name__ == "__main__":
    app.run(main)
