#!/usr/bin/env python3
"""Generate a shell script that relocates extracted '.Pictures.*' trees.

Some directories in the 'hashes' table (see hash_dir.py) contain a path
component matching '.Pictures.<name>' -- a marker directory produced by
some extraction step (e.g. '.Pictures.Thumb'). For every such file, this
tool computes a destination relative to --output_dir by dropping
everything up to and including the '.Pictures.' prefix of that
component, using '<name>' as the new top-level directory, and keeping
the rest of the path unchanged, e.g.:

    .Pictures.Thumb/1998/ancient/Apple_Salikh.jpg
        -> <output_dir>/Thumb/1998/ancient/Apple_Salikh.jpg

When several source files map to the same destination, the one with the
latest mtime is moved there. Of the rest, any with the same hash as the
moved copy are redundant and get `rm -vf --`ed; any with a *different*
hash (an unexpected same-target collision) are left in place, noted in
a comment for manual review.

If --target_db is given (a 'hashes'-format database for --output_dir
itself, e.g. produced by hash_dir.py run against it), a destination that
already exists there is not moved to again: the source file is instead
`rm`-ed, since --output_dir already has a copy of it.

This tool only WRITES a shell script, to stdout. It never moves or
deletes anything itself; review the generated script before running it.

Usage:
    thumbs_move.py
        --output_dir /zoo/Thumbs
        --target_db /zoo/Thumbs/hashes.db
        ~/zoo.db
        > move_thumbs.sh
"""

import os
import re
import shlex
import sqlite3
import sys
from collections import defaultdict
from datetime import datetime, timezone

from absl import app
from absl import flags
from absl import logging

FLAGS = flags.FLAGS

flags.DEFINE_string(
    "output_dir", None,
    "Directory that relocated files are placed under, e.g. 'Thumbs'.")
flags.DEFINE_string(
    "target_db", None,
    "Path to a 'hashes'-format sqlite3 database for --output_dir itself; "
    "a destination that already exists there gets its source file removed "
    "instead of moved.")
flags.mark_flag_as_required("output_dir")

MARKER_RE = re.compile(r"^\.Pictures\.(.+)$")


def load_files(db_path):
    """Return [(filename, hash, mtime), ...] from the 'hashes' table."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        return conn.execute("SELECT filename, hash, mtime FROM hashes").fetchall()
    finally:
        conn.close()


def load_target_filenames(db_path):
    """Return the set of filenames in --target_db's 'hashes' table."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        return {row[0] for row in conn.execute("SELECT filename FROM hashes")}
    finally:
        conn.close()


def classify(filename):
    """Classify `filename` against the '.Pictures.<name>' convention.

    Returns:
        target_rel  -- '<name>/<rest of path>' to use under --output_dir,
                        for the first path component matching
                        '.Pictures.<name>'.
        None        -- no matching component, or the match was the final
                        (filename) component, leaving no file to move.
    """
    parts = filename.split("/")
    for i, part in enumerate(parts):
        m = MARKER_RE.match(part)
        if m:
            rest = parts[i + 1:]
            if not rest:
                return None
            return "/".join([m.group(1)] + rest)
    return None


def group_by_target(rows):
    """Return target_rel -> [(mtime, filename, hash), ...] for matching files."""
    targets = defaultdict(list)
    for filename, hash_, mtime in rows:
        target_rel = classify(filename)
        if target_rel is not None:
            targets[target_rel].append((mtime, filename, hash_))
    return targets


def pick_winner(entries):
    """Pick the entry with the latest mtime; ties broken by path (deterministic)."""
    def key(entry):
        mtime, filename, hash_ = entry
        return (mtime if mtime is not None else float("-inf"), filename)

    return max(entries, key=key)


def build_script(db_path, output_dir, targets, target_filenames):
    lines = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by thumbs_move.py -- DO NOT RUN WITHOUT REVIEWING FIRST.")
    lines.append(f"# Source database: {db_path}")
    lines.append(f"# Output directory: {output_dir}")
    lines.append(f"# Generated at:    {datetime.now(timezone.utc).isoformat()}")
    lines.append("# Run from the directory that the paths below are relative to.")
    lines.append("set -e")
    lines.append("")

    num_moved = 0
    num_removed = 0
    num_dup_removed = 0
    num_dup_skipped = 0
    total = len(targets)
    for i, target_rel in enumerate(sorted(targets), start=1):
        entries = targets[target_rel]
        winner_mtime, winner_file, winner_hash = pick_winner(entries)
        dest = os.path.join(output_dir, target_rel)
        for mtime, filename, hash_ in sorted(entries, key=lambda e: e[1]):
            if filename == winner_file:
                continue
            if hash_ == winner_hash:
                lines.append(f"# duplicate of {winner_file} (same hash): {filename}")
                lines.append(f"rm -vf -- {shlex.quote(filename)}")
                num_dup_removed += 1
            else:
                lines.append(
                    "# duplicate target with a DIFFERENT hash, left in "
                    f"place: {filename}")
                num_dup_skipped += 1
        if target_filenames is not None and target_rel in target_filenames:
            lines.append(f"# already exists in --target_db: {dest}")
            lines.append(f"rm -vf -- {shlex.quote(winner_file)}")
            num_removed += 1
        else:
            lines.append(f"mkdir -vp -- {shlex.quote(os.path.dirname(dest))}")
            lines.append(f"mv -v -- {shlex.quote(winner_file)} {shlex.quote(dest)}")
            num_moved += 1
        lines.append("")

        if i % 100 == 0:
            pct = i / total * 100
            lines.append(f"echo ======= Progress {pct:.2f}% ========")
            lines.append("")

    return ("\n".join(lines) + "\n",
            num_moved, num_removed, num_dup_removed, num_dup_skipped)


def main(argv):
    if len(argv) != 2:
        raise app.UsageError(
            "Expected exactly one positional argument: path to the sqlite3 "
            "database (got: %s)" % argv[1:])
    database = argv[1]

    rows = load_files(database)
    targets = group_by_target(rows)
    target_filenames = (
        load_target_filenames(FLAGS.target_db) if FLAGS.target_db else None)
    script, num_moved, num_removed, num_dup_removed, num_dup_skipped = build_script(
        database, FLAGS.output_dir, targets, target_filenames)

    sys.stdout.write(script)

    logging.info(
        "%d files to move, %d files to remove (already present in "
        "--target_db), %d redundant same-hash duplicates to remove, %d "
        "different-hash collisions left in place",
        num_moved, num_removed, num_dup_removed, num_dup_skipped)
    logging.info("Review the script before running it -- nothing was moved "
                 "or removed.")


if __name__ == "__main__":
    app.run(main)
