"""Shared, flag-free classification logic for compare.py and apply.py (ticket 137).

Deliberately defines no absl flags and imports nothing that does, so it is safe to import directly
into a test process (unlike compare.py/apply.py themselves, which each define required flags of
their own -- see tests/test_archive_compare.py for why that matters). See compare.py's module
docstring for what "have"/"rejected"/"lost"/"new" mean.
"""

import json
import os
import shlex
import shutil
import sqlite3

from absl import logging

BUCKETS = ("have", "rejected", "lost", "new")
COPY_BUCKETS = ("lost", "new")


def load_live(path):
  """(file_hashes: set, decisions: {hash: {"rating":, "fav":, "rated_at":}}) from a ticket-134
  (photoapp.export_catalog) export."""
  file_hashes = set()
  decisions = {}
  with open(path) as f:
    for line in f:
      line = line.strip()
      if not line:
        continue
      record = json.loads(line)
      if record["type"] == "file":
        file_hashes.add(record["hash"])
      elif record["type"] == "decision":
        decisions[record["hash"]] = {"rating": record["rating"], "fav": record["fav"],
                                     "rated_at": record["rated_at"]}
  return file_hashes, decisions


def load_target(db_path):
  """{filename: hash} from a catalog.py/import_sha224sum.py-format database."""
  conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
  try:
    return dict(conn.execute("SELECT filename, hash FROM hashes"))
  finally:
    conn.close()


def classify(file_hash, file_hashes, decisions):
  """"have" wins regardless of what a decision says -- the live library is authoritative over
  anything a past decision recorded (see docs/tickets/135.md)."""
  if file_hash in file_hashes:
    return "have"
  decision = decisions.get(file_hash)
  if decision is None:
    return "new"
  return "rejected" if decision["rating"] == -1 else "lost"


def compare(target_files, file_hashes, decisions):
  """{bucket: [(filename, hash), ...]}, filename-sorted within each bucket."""
  buckets = {b: [] for b in BUCKETS}
  for filename, file_hash in sorted(target_files.items()):
    buckets[classify(file_hash, file_hashes, decisions)].append((filename, file_hash))
  return buckets


def compare_reverse(target_files, file_hashes):
  """Live hashes absent from the target copy at all, as a sorted list of hashes (a live hash may
  correspond to several paths on this machine; the report is about content, not any one path)."""
  target_hashes = set(target_files.values())
  return sorted(file_hashes - target_hashes)


def format_report(buckets):
  lines = ["# tools/archive/compare.py report"]
  for b in BUCKETS:
    lines.append(f"# {b}: {len(buckets[b])}")
  lines.append("#")
  lines.append("# bucket\tpath\thash")
  for b in BUCKETS:
    for filename, file_hash in buckets[b]:
      lines.append(f"{b}\t{filename}\t{file_hash}")
  return "\n".join(lines) + "\n"


def format_reverse_report(only_live_hashes):
  lines = [f"# tools/archive/compare.py --reverse report: {len(only_live_hashes)} live hash(es) "
          "absent from the target copy", "#"]
  lines.extend(only_live_hashes)
  return "\n".join(lines) + "\n"


# --- apply.py (ticket 137): acting on a classification -----------------------------------------


def plan(buckets, pictures_dir):
  """[(bucket, source, dest)] for every actionable (non-"have") entry. source is a path relative
  to the target copy's own root; dest is the absolute pictures_dir destination for a 'lost'/'new'
  copy, or None for 'rejected' (nothing is ever copied for that bucket)."""
  actions = []
  for bucket, entries in buckets.items():
    if bucket == "have":
      continue
    for filename, _file_hash in entries:
      dest = os.path.join(pictures_dir, filename) if bucket in COPY_BUCKETS else None
      actions.append((bucket, filename, dest))
  return actions


def format_script(actions, target_root, pictures_dir):
  """A reviewable shell script for every action: `rm` for 'rejected' (on the target copy, never
  run by this tool itself), `mkdir -p`+`cp -n` (never overwrite) for 'lost'/'new' copies into
  pictures_dir."""
  lines = ["#!/bin/sh",
          "# Generated by tools/archive/apply.py -- DO NOT RUN WITHOUT REVIEWING FIRST.",
          f"# target_root:  {target_root}",
          f"# pictures_dir: {pictures_dir}",
          "set -e", ""]
  for bucket, source, dest in sorted(actions):
    src_abs = shlex.quote(os.path.join(target_root, source))
    if bucket == "rejected":
      lines.append(f"rm -v -- {src_abs}")
    else:
      lines.append(f"mkdir -p -- {shlex.quote(os.path.dirname(dest))}")
      lines.append(f"cp -v -n -- {src_abs} {shlex.quote(dest)}")
  return "\n".join(lines) + "\n"


def apply_copies(actions, target_root):
  """Perform every 'lost'/'new' copy for real ('rejected' is never touched here -- see
  format_script's docstring). Returns (copied, skipped): skipped lists (dest, reason) for a
  destination that already exists (never overwritten)."""
  copied, skipped = [], []
  for bucket, source, dest in actions:
    if bucket not in COPY_BUCKETS:
      continue
    if os.path.exists(dest):
      skipped.append((dest, "already exists"))
      continue
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    shutil.copy2(os.path.join(target_root, source), dest)
    copied.append(dest)
    logging.info("copied %s -> %s", source, dest)
  return copied, skipped
